# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-20 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_type',
            field=models.CharField(max_length=3),
        ),
    ]
