# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-20 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batmobile', '0001_initial'),
        ('hospital', '0001_initial'),
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=2)),
                ('amount', models.BigIntegerField()),
                ('used', models.BooleanField()),
                ('arrive_date', models.DateField()),
                ('used_by_date', models.DateField()),
                ('bat_mobileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batmobile.Batmobile')),
                ('donorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.Donor')),
                ('hospitalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital')),
            ],
        ),
    ]
