# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batmobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=2)),
                ('amount', models.BigIntegerField()),
                ('used', models.BooleanField()),
                ('arrive_date', models.DateField()),
                ('used_by_date', models.DateField()),
                ('bat_mobileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloods.Batmobile')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=1)),
                ('blood_type', models.CharField(max_length=2)),
                ('DOB', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('last_verified', models.DateField()),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='donor',
            name='linking_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloods.Hospital'),
        ),
        migrations.AddField(
            model_name='blood',
            name='donorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloods.Donor'),
        ),
        migrations.AddField(
            model_name='blood',
            name='hospitalId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloods.Hospital'),
        ),
    ]
