# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-20 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood',
            name='blood_type',
        ),
    ]
